#### Importing the standard Libraries

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
from pandas import DataFrame, Series
import tensorflow as tf
import numpy as np
import os
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib import ticker
import matplotlib.colors as mc

#### Importing the GBvideo Dataset 

In [11]:
gb_df = pd.read_csv('GBvideo.csv')
gb_df.head(10)

trending_date                                              title  \
0    11/14/2017      John Lewis Christmas Ad 2017 - #MozTheMonster   
1    11/14/2017          Taylor Swift: …Ready for It? (Live) - SNL   
2    11/14/2017         Eminem - Walk On Water (Audio) ft. Beyoncé   
3    11/14/2017  Goals from Salford City vs Class of 92 and Fri...   
4    11/14/2017  Dashcam captures truck's near miss with child ...   
5    11/14/2017                       How My Relationship Started!   
6    11/14/2017        Ed Sheeran - Perfect (Official Music Video)   
7    11/14/2017                      CHRISTMAS HAS GONE TO MY HEAD   
8    11/14/2017   Elbow - Golden Slumbers (John Lewis Advert 2017)   
9    11/14/2017  Jennifer Lopez - Amor, Amor, Amor (Official Vi...   

                channel_title  category_id               publish_time  \
0                  John Lewis           26  2017-11-10 07:38:29+00:00   
1         Saturday Night Live           24  2017-11-12 06:24:44+00:00   
2                  EminemVEVO           10  2017-11-10 17:00:03+00:00   
3  Salford City Football Club           17  2017-11-13 02:30:38+00:00   
4            Cute Girl Videos           25  2017-11-13 01:45:13+00:00   
5          PointlessBlogVlogs           24  2017-11-11 17:00:00+00:00   
6                  Ed Sheeran           10  2017-11-09 11:04:14+00:00   
7                  MoreZoella           22  2017-11-10 19:19:43+00:00   
8                   ElbowVEVO           10  2017-11-10 08:00:01+00:00   
9           JenniferLopezVEVO           10  2017-11-10 15:00:00+00:00   

                                                tags     views    likes  \
0  christmas|"john lewis christmas"|"john lewis"|...   7224515    55681   
1  SNL|"Saturday Night Live"|"SNL Season 43"|"Epi...   1053632    25561   
2  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   787420   
3  Salford City FC|"Salford City"|"Salford"|"Clas...     27833      193   
4                                             [none]      9815       30   
5  pointlessblog|"pointlessblogtv"|"pointlessblog...   1182775    52708   
6  edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...  33523622  1634124   
7  zoe sugg|"zoella"|"zoe"|"vlog"|"vlogging"|"vlo...   1164201    57309   
8  Elbow|"Golden"|"Slumbers"|"Polydor"|"Alternative"    154494     2163   
9  Jennifer Lopez ft. Wisin|"Jennifer Lopez ft. W...   9548677   190084   

   dislikes  comment_count          trending_duration  
0     10247           9479  0 days 06:46:59.000000000  
1      2294           2757  0 days 16:30:00.000000000  
2     43420         125882  1 days 04:54:36.000000000  
3        12             37  0 days 12:59:56.000000000  
4         2             30  1 days 05:58:19.000000000  
5      1431           2333  0 days 04:52:37.000000000  
6     21082          85067  1 days 18:22:43.000000000  
7       749            624  1 days 02:09:23.000000000  
8       147            211  0 days 09:59:37.000000000  
9     15015          11473  0 days 10:14:44.000000000

In [12]:
gb_df.describe()

category_id         views         likes      dislikes  comment_count
count  38916.000000  3.891600e+04  3.891600e+04  3.891600e+04   3.891600e+04
mean      16.827937  5.911944e+06  1.345196e+05  7.612560e+03   1.308835e+04
std        7.752728  1.900121e+07  3.499893e+05  5.095683e+04   5.066740e+04
min        1.000000  8.510000e+02  0.000000e+00  0.000000e+00   0.000000e+00
25%       10.000000  2.515272e+05  5.897000e+03  2.000000e+02   6.790000e+02
50%       20.000000  9.818890e+05  2.518250e+04  8.210000e+02   2.478000e+03
75%       24.000000  3.683628e+06  1.140892e+05  3.357500e+03   9.241500e+03
max       43.000000  4.245389e+08  5.613827e+06  1.944971e+06   1.626501e+06

### Now we need to calculate the engagement rate 

##### As per the formula, Engagement Rate = (comment_count + like + dislike)/ views x 100

In [13]:
comment_count = gb_df['comment_count'].values
comment_count[:5]

array([  9479,   2757, 125882,     37,     30], dtype=int64)

In [14]:
likes = gb_df['likes'].values
likes[:5]

array([ 55681,  25561, 787420,    193,     30], dtype=int64)

In [15]:
dislikes = gb_df["dislikes"].values
dislikes[:5]

array([10247,  2294, 43420,    12,     2], dtype=int64)

In [16]:
views = gb_df["views"].values
views[:5]

array([ 7224515,  1053632, 17158579,    27833,     9815], dtype=int64)

In [17]:
total = (comment_count + likes + dislikes)

In [19]:
Engagement_rate = total/views*100

In [20]:
Engagement_rate

array([1.04376557, 2.90537873, 5.57576475, 0.86947149, 0.63168619])

#### adding Variable to the dataset and saving dataset to disk

In [21]:
gb_df['ER_View'] = Engagement_rate

In [22]:
gb_df.to_csv("result_gbvideos.csv")